# Generated by Django 4.1.2 on 2022-12-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Niveau', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='experiencesStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('Entreprise', models.CharField(max_length=100)),
                ('dateDebut', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='diplomesFormations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.types')),
            ],
        ),
    ]
