# Generated by Django 4.1.2 on 2022-12-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomesformations',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.types'),
        ),
    ]
